controller_list:
  - name: fake_right_arm_controller
    joints:
      - R_ShoulderPitch
      - R_ShoulderRoll
      - R_ShoulderYaw
      - R_ElbowRoll
      - R_WristYaw
      - R_WristRoll
      - R_HandYaw
  - name: fake_right_hand_controller
    joints:
      - R_HandYaw